### ISSUE TITLE
logの整理

### ISSUE THREAD

**Issue by tomofuji-dev** [NaoyaFukuma/webserv#115]
## Overview
Please provide an overview of the issue you are creating.
ex) I want to adapt the style of the header.

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [ ] XXXX
- [ ] XXXX
- [ ] XXXX

**Comment by tomofuji-dev** [comment]
```
#ifndef DEBUG
  #define DEBUG_PRINT(fmt, ...) \
    do {} while(0);
#else
  #define DEBUG_PRINT(fmt, ...) \
    do { printf(fmt, ##__VA_ARGS__); } while(0);
#endif
```

**Comment by NaoyaFukuma** [comment]
上記のマクロを”define.hpp”に記載し、このヘッダファイルの中でマクロ自体は一括管理できるようにした。
