### ISSUE TITLE
recvの致命的なエラーをハンドリングする方法

### ISSUE THREAD

**Issue by tomofuji-dev** [NaoyaFukuma/webserv#14]
## Overview
相手が接続を切るシナリオは、EPOLLHUP | EPOLLRDHUPで拾えるので、EAGAINは捨て置いて良い

recvの後にerrnoを見れないため、recv中は以下のerrnoに対応するためにsignalを無視する必要がある
データを受信する前に、シグナルが配送されて割り込まれた。 [signal](https://linuxjm.osdn.jp/html/LDP_man-pages/man7/signal.7.html)(7) 参照。

## Task

- [x] プログラム全体でSIGPIPEを無視する
- [ ] recv/send途中ではシグナルを無視する

**Comment by NaoyaFukuma** [comment]
14-recvの致命的なエラーをハンドリングする方法
でSIGPIPEへの対応を行った。

recv(), send()中のシグナルはあえて無視しないで身を任せる、、
