### ISSUE TITLE
unit-test

### ISSUE THREAD

**Issue by Chanmachan** [NaoyaFukuma/webserv#24]
## Overview
GitHubActions用もかねてParserとかのユニットテストを実装する

## Purpose
リファクタとマージしたりしてぶっ壊れないように、万が一壊れても場所をすぐみつけられるように

## Task
Break down and manage your tasks.
- [x] とりあえずテストケース追加してみる
- [x] Actions用のyml書く
- [x] (cmake使うか考える)

**Comment by Chanmachan** [comment]
何も考えずに書きますが、
cmakeはテストの自動化(コンパイルから実行までをパターン化、簡易化？)する点で使える可能性も微レ存

**Comment by NaoyaFukuma** [comment]
unit testをを実装するというこのissueの目的は達成しているので、このissueはCloseして、テストの拡充とともにissue管理するのはどうでしょうか？

**Comment by Chanmachan** [comment]
> unit testをを実装するというこのissueの目的は達成しているので、このissueはCloseして、テストの拡充とともにissue管理するのはどうでしょうか？

賛成です！

**Comment by NaoyaFukuma** [comment]
上記の通り、このissueはClose

**Comment by Chanmachan** [comment]
プルリク承認されたら閉じるつもりだったんですけどマージしちゃっても大丈夫ですかね？

**Comment by NaoyaFukuma** [comment]
先走りましたｗ
