### ISSUE TITLE
SocketBuff::AddStringを修正

### ISSUE THREAD

**Issue by tomofuji-dev** [NaoyaFukuma/webserv#32]

**Comment by NaoyaFukuma** [comment]
現状、AddString時に、データ量に合わせてバッファとして使っているメモリの動的確保が起こっていることで、
Addstring時にデータの欠損が起きている可能性がある。

エコーサーバー時点では、このまま開発をすすめるが、
HTTPリクエストのパースを実装したあとも同様の問題を抱えるなら、
バッファを固定長にすることで解決を試みることを検討したいと思う。

**Comment by NaoyaFukuma** [comment]
vector<char>によるバッファリングの実装に変更し回収した
