### ISSUE TITLE
request parser残りタスク

### ISSUE THREAD

**Issue by tomofuji-dev** [NaoyaFukuma/webserv#77]
## Overview
Please provide an overview of the issue you are creating.
ex) I want to adapt the style of the header.

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [x] "8\r\ndata\r\n\r\n”について考える
- [x] 大まかな処理の流れを作る
- [ ] headerがCOMPLETEになる条件を見直す
- [ ] #74

**Comment by Chanmachan** [comment]
あとヘッダーファイルのごちゃごちゃも綺麗にしたい
